unitTests server
Stern-Hillpocken/tempo-slack pull request #34
Opened 2024-02-16 18:45 UTC by studentsjj

tests for server

2024-02-19 08:24 UTC, Stern-Hillpocken requested changes

2024-02-19 08:24 UTC, Stern-Hillpocken commented on back/src/test/java/firstgroup/temposlack/TempoSlackServerTests.java
Sur les tests tu veux vérifier que les méthodes crées fonctionnent bien, donc tu dois utiliser ces méthodes. Donc vraiment faire comme si le front envoyait le json, donc avec l'utilisation des DTO et les méthodes addServer(), etc.

2024-02-19 08:24 UTC, Stern-Hillpocken commented on back/src/test/java/firstgroup/temposlack/TempoSlackServerTests.java
> +        User user = new User("toto", "password", "toto@gmail.com", "licorne");
Regarde peut-être comment j'ai fais pour créer un User dans mes tests.
D'autant que en test réel ça ne devrait pas passer car le password doit contenir un signe non-word (!w)

2024-02-19 08:24 UTC, Stern-Hillpocken commented on back/src/test/java/firstgroup/temposlack/TempoSlackServerTests.java
> +        assertEquals("toto", server.getUserList().get(0).getPseudo());
On a une méthode server.isUserInServer(user) qu'il serait bien de tester.

2024-02-19 17:24 UTC, studentsjj commented on back/src/test/java/firstgroup/temposlack/TempoSlackServerTests.java
Je souhaitais faire des tests unitaires et donc juste tester le service, c'est pour cela que je n'ai pas utilisé SpringBootTest.

2024-02-20 16:41 UTC, Stern-Hillpocken approved these changes

2024-02-20 16:42 UTC, Stern-Hillpocken approved these changes

2024-02-20 16:42 UTC, merged